services:
  - type: web
    name: flask-webform-project
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    region: singapore
    plan: free
    branch: main
    autoDeploy: true